// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomHeader: typeof import('./src/components/mainPat/CustomHeader.vue')['default']
    LoadingIcon: typeof import('./src/components/svgIcon/LoadingIcon.vue')['default']
    RequestLoading: typeof import('./src/components/interactions/RequestLoading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./src/components/mainPat/TabBar.vue')['default']
    VanCell: typeof import('vant/es')['Cell']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanSticky: typeof import('vant/es')['Sticky']
  }
}
